### ISSUE TITLE
新增容器或者镜像备份到本地的功能

### ISSUE THREAD

**Issue by taoes** [taoes/SimpleDocker#4]

**Comment by taoes** [comment]
此功能开发中...

**Comment by BlueSpiderGIGI** [comment]
对啊，这个很重要呢，加油哦

**Comment by taoes** [comment]
> 对啊，这个很重要呢，加油哦

预计下周发布新版本的时候发布此功能，感谢关注！

**Comment by taoes** [comment]
容器、镜像备份到本地服务器的功能已发布（  版本V0.0.6 ），部署更新脚本如下，请修改docker-compose 文件中的镜像版本号为0.0.6 ，然后重新执行`docker-compose up -d` 即可

```yaml
# yaml 配置实例
version: '3'
services:
  redis:
    image: redis:latest
  web:
    image: registry.cn-hangzhou.aliyuncs.com/seven-tao/simple-docker:0.0.6
    ports:
      - "9091:4050"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - redis
```


**如果需要持久化容器/镜像的备份文件，请在 volumes 标签下新增配置 - 宿主机目录:/tmp/back, 如 - /home/data/back:/tmp/back**
