### ISSUE TITLE
建议增加登陆页面的 验证码 哈

### ISSUE THREAD

**Issue by xiaoyanbot** [taoes/SimpleDocker#8]
运维领域，等级保障评测，强制要求引入的系统，登陆时有验证码

建议增加登陆验证码，方便更多用户的环境导入本工具哈，感谢  ^_^

**Comment by taoes** [comment]
好的，下个版本将会添加验证码登录的功能

**Comment by taoes** [comment]
登录页面的验证码功能已发布 V0.0.7 版本，请更新 docker-compose.yml 文件内容修改版本为 0.0.7 后 `docker-compose up -d` 重新部署应用即可 
```yml
# yaml 配置实例
version: '3'
services:
  redis:
    image: redis:latest
  web:
    image: registry.cn-hangzhou.aliyuncs.com/seven-tao/simple-docker:0.0.7
    ports:
      - "9091:4050"
    volumes:
      - /tmp/simple-docker/back:/tmp/back
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - redis

```
